// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/example.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	_ "zap"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string            `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string            `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	EmployeeNumber       int64             `protobuf:"varint,4,opt,name=employee_number,json=employeeNumber,proto3" json:"employee_number,omitempty"`
	PhysicalDesk         string            `protobuf:"bytes,6,opt,name=physical_desk,json=physicalDesk,proto3" json:"physical_desk,omitempty"`
	Service              *ServiceMsg       `protobuf:"bytes,8,opt,name=service,proto3" json:"service,omitempty"`
	Blocked              []string          `protobuf:"bytes,9,rep,name=blocked,proto3" json:"blocked,omitempty"`
	Extra                map[string]string `protobuf:"bytes,10,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	List                 []*ServiceMsg     `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmployeeNumber() int64 {
	if m != nil {
		return m.EmployeeNumber
	}
	return 0
}

func (m *User) GetPhysicalDesk() string {
	if m != nil {
		return m.PhysicalDesk
	}
	return ""
}

func (m *User) GetService() *ServiceMsg {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *User) GetBlocked() []string {
	if m != nil {
		return m.Blocked
	}
	return nil
}

func (m *User) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *User) GetList() []*ServiceMsg {
	if m != nil {
		return m.List
	}
	return nil
}

type Parent struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Child                *Parent_Child `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Parent) Reset()         { *m = Parent{} }
func (m *Parent) String() string { return proto.CompactTextString(m) }
func (*Parent) ProtoMessage()    {}
func (*Parent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1}
}

func (m *Parent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent.Unmarshal(m, b)
}
func (m *Parent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent.Marshal(b, m, deterministic)
}
func (m *Parent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent.Merge(m, src)
}
func (m *Parent) XXX_Size() int {
	return xxx_messageInfo_Parent.Size(m)
}
func (m *Parent) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent.DiscardUnknown(m)
}

var xxx_messageInfo_Parent proto.InternalMessageInfo

func (m *Parent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Parent) GetChild() *Parent_Child {
	if m != nil {
		return m.Child
	}
	return nil
}

type Parent_Child struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GrandChild           *Parent_Child_GrandChild `protobuf:"bytes,2,opt,name=grand_child,json=grandChild,proto3" json:"grand_child,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Parent_Child) Reset()         { *m = Parent_Child{} }
func (m *Parent_Child) String() string { return proto.CompactTextString(m) }
func (*Parent_Child) ProtoMessage()    {}
func (*Parent_Child) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1, 0}
}

func (m *Parent_Child) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent_Child.Unmarshal(m, b)
}
func (m *Parent_Child) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent_Child.Marshal(b, m, deterministic)
}
func (m *Parent_Child) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent_Child.Merge(m, src)
}
func (m *Parent_Child) XXX_Size() int {
	return xxx_messageInfo_Parent_Child.Size(m)
}
func (m *Parent_Child) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent_Child.DiscardUnknown(m)
}

var xxx_messageInfo_Parent_Child proto.InternalMessageInfo

func (m *Parent_Child) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Parent_Child) GetGrandChild() *Parent_Child_GrandChild {
	if m != nil {
		return m.GrandChild
	}
	return nil
}

type Parent_Child_GrandChild struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parent_Child_GrandChild) Reset()         { *m = Parent_Child_GrandChild{} }
func (m *Parent_Child_GrandChild) String() string { return proto.CompactTextString(m) }
func (*Parent_Child_GrandChild) ProtoMessage()    {}
func (*Parent_Child_GrandChild) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1, 0, 0}
}

func (m *Parent_Child_GrandChild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent_Child_GrandChild.Unmarshal(m, b)
}
func (m *Parent_Child_GrandChild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent_Child_GrandChild.Marshal(b, m, deterministic)
}
func (m *Parent_Child_GrandChild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent_Child_GrandChild.Merge(m, src)
}
func (m *Parent_Child_GrandChild) XXX_Size() int {
	return xxx_messageInfo_Parent_Child_GrandChild.Size(m)
}
func (m *Parent_Child_GrandChild) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent_Child_GrandChild.DiscardUnknown(m)
}

var xxx_messageInfo_Parent_Child_GrandChild proto.InternalMessageInfo

func (m *Parent_Child_GrandChild) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ServiceMsg struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceMsg) Reset()         { *m = ServiceMsg{} }
func (m *ServiceMsg) String() string { return proto.CompactTextString(m) }
func (*ServiceMsg) ProtoMessage()    {}
func (*ServiceMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{2}
}

func (m *ServiceMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceMsg.Unmarshal(m, b)
}
func (m *ServiceMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceMsg.Marshal(b, m, deterministic)
}
func (m *ServiceMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceMsg.Merge(m, src)
}
func (m *ServiceMsg) XXX_Size() int {
	return xxx_messageInfo_ServiceMsg.Size(m)
}
func (m *ServiceMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceMsg proto.InternalMessageInfo

func (m *ServiceMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "example.User")
	proto.RegisterMapType((map[string]string)(nil), "example.User.ExtraEntry")
	proto.RegisterType((*Parent)(nil), "example.Parent")
	proto.RegisterType((*Parent_Child)(nil), "example.Parent.Child")
	proto.RegisterType((*Parent_Child_GrandChild)(nil), "example.Parent.Child.GrandChild")
	proto.RegisterType((*ServiceMsg)(nil), "example.ServiceMsg")
}

func init() { proto.RegisterFile("example/example.proto", fileDescriptor_1c78cffa5d645ba4) }

var fileDescriptor_1c78cffa5d645ba4 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcb, 0x8e, 0x94, 0x40,
	0x14, 0x86, 0xc3, 0xad, 0x7b, 0x38, 0x38, 0xa3, 0x29, 0x9d, 0xa4, 0x42, 0x5c, 0x10, 0x34, 0x91,
	0xc4, 0xc8, 0x98, 0x76, 0x33, 0x71, 0xe7, 0x65, 0xe2, 0xca, 0x89, 0x29, 0xe3, 0x9a, 0x54, 0xc3,
	0xb1, 0x87, 0x50, 0x5c, 0x52, 0xc5, 0x4c, 0x9a, 0x79, 0x0b, 0x1f, 0xc0, 0xf7, 0x70, 0xe7, 0x9b,
	0x19, 0x43, 0x01, 0x4d, 0x67, 0xba, 0x57, 0x9c, 0xf3, 0xff, 0x5f, 0xfd, 0x07, 0x0e, 0x05, 0xe7,
	0xb8, 0xe5, 0x65, 0x23, 0xf0, 0x62, 0x7c, 0xc6, 0x8d, 0xac, 0xdb, 0x9a, 0x2c, 0xc7, 0xd6, 0x3f,
	0xbd, 0xe7, 0xcd, 0xc5, 0x3d, 0x6f, 0x06, 0x3d, 0xfc, 0x65, 0x81, 0xfd, 0x43, 0xa1, 0x24, 0x67,
	0x60, 0xe6, 0x19, 0x35, 0x02, 0x23, 0x72, 0x99, 0x99, 0x67, 0xe4, 0x25, 0xc0, 0xcf, 0x5c, 0xaa,
	0x36, 0xa9, 0x78, 0x89, 0xd4, 0xec, 0xf5, 0x8f, 0xce, 0x9f, 0x7f, 0xbf, 0x2d, 0x83, 0xb9, 0xda,
	0xb8, 0xe6, 0x25, 0x92, 0x10, 0x5c, 0xc1, 0x27, 0xc8, 0xda, 0x87, 0x4e, 0x7a, 0x5d, 0x33, 0x31,
	0x3c, 0xc6, 0xb2, 0x11, 0x75, 0x87, 0x98, 0x54, 0xb7, 0xe5, 0x1a, 0x25, 0xb5, 0x03, 0x23, 0xb2,
	0x26, 0xf2, 0x6c, 0x72, 0xaf, 0xb5, 0x49, 0x5e, 0xc0, 0x69, 0x73, 0xd3, 0xa9, 0x3c, 0xe5, 0x22,
	0xc9, 0x50, 0x15, 0x74, 0xa1, 0x5f, 0xea, 0xd1, 0x24, 0x7e, 0x46, 0x55, 0x90, 0x37, 0xb0, 0x54,
	0x28, 0xef, 0xf2, 0x14, 0xe9, 0x49, 0x60, 0x44, 0xde, 0xea, 0x69, 0x3c, 0x7d, 0xf0, 0xf7, 0x41,
	0xff, 0xaa, 0x36, 0x6c, 0x62, 0x08, 0x85, 0xe5, 0x5a, 0xd4, 0x69, 0x81, 0x19, 0x75, 0x03, 0x2b,
	0x72, 0xd9, 0xd4, 0x92, 0x18, 0x1c, 0xdc, 0xb6, 0x92, 0x53, 0x08, 0xac, 0xc8, 0x5b, 0xd1, 0x5d,
	0x4c, 0xbf, 0x95, 0xf8, 0xaa, 0xb7, 0xae, 0xaa, 0x56, 0x76, 0x6c, 0xc0, 0xc8, 0x2b, 0xb0, 0x45,
	0xae, 0x5a, 0xea, 0x69, 0xfc, 0xe8, 0x54, 0x0d, 0xf8, 0x97, 0x00, 0xf3, 0x69, 0xf2, 0x04, 0xac,
	0x02, 0xbb, 0x71, 0xbf, 0x7d, 0x49, 0x9e, 0x81, 0x73, 0xc7, 0xc5, 0xed, 0xb8, 0x5b, 0x36, 0x34,
	0xef, 0xcd, 0x4b, 0x23, 0xfc, 0x6b, 0xc0, 0xe2, 0x1b, 0x97, 0x58, 0xb5, 0x07, 0x7f, 0xe5, 0x35,
	0x38, 0xe9, 0x4d, 0x2e, 0x32, 0x7d, 0xc8, 0x5b, 0x9d, 0xef, 0xc6, 0x0f, 0x7c, 0xfc, 0xa9, 0x37,
	0xd9, 0xc0, 0xf8, 0x5b, 0x70, 0x74, 0x7f, 0x90, 0xf2, 0x01, 0xbc, 0x8d, 0xe4, 0x55, 0x96, 0xec,
	0x67, 0x05, 0x47, 0xb3, 0xe2, 0x2f, 0x3d, 0x38, 0xc4, 0xc2, 0x66, 0x57, 0xfb, 0xcf, 0x01, 0x66,
	0xe7, 0xe1, 0x80, 0xf0, 0x2d, 0xc0, 0xbc, 0x8f, 0x83, 0xf1, 0x04, 0xec, 0xf9, 0x52, 0x31, 0x5d,
	0xaf, 0x17, 0xfa, 0x3a, 0xbe, 0xfb, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x1d, 0xe0, 0x63, 0xbf,
	0x02, 0x00, 0x00,
}
