// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/example.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/kei2100/protoc-gen-zap/zap"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_Sex int32

const (
	User_SEX_NOT_KNOWN      User_Sex = 0
	User_SEX_MALE           User_Sex = 1
	User_SEX_FEMALE         User_Sex = 2
	User_SEX_NOT_APPLICABLE User_Sex = 9
)

var User_Sex_name = map[int32]string{
	0: "SEX_NOT_KNOWN",
	1: "SEX_MALE",
	2: "SEX_FEMALE",
	9: "SEX_NOT_APPLICABLE",
}

var User_Sex_value = map[string]int32{
	"SEX_NOT_KNOWN":      0,
	"SEX_MALE":           1,
	"SEX_FEMALE":         2,
	"SEX_NOT_APPLICABLE": 9,
}

func (x User_Sex) String() string {
	return proto.EnumName(User_Sex_name, int32(x))
}

func (User_Sex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0, 0}
}

type User struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string            `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string            `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	EmployeeNumber       int64             `protobuf:"varint,4,opt,name=employee_number,json=employeeNumber,proto3" json:"employee_number,omitempty"`
	PhysicalDesk         string            `protobuf:"bytes,6,opt,name=physical_desk,json=physicalDesk,proto3" json:"physical_desk,omitempty"`
	Service              *ServiceMsg       `protobuf:"bytes,8,opt,name=service,proto3" json:"service,omitempty"`
	Blocked              []string          `protobuf:"bytes,9,rep,name=blocked,proto3" json:"blocked,omitempty"`
	Extra                map[string]string `protobuf:"bytes,10,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	List                 []*ServiceMsg     `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	Sex                  User_Sex          `protobuf:"varint,12,opt,name=sex,proto3,enum=example.User_Sex" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmployeeNumber() int64 {
	if m != nil {
		return m.EmployeeNumber
	}
	return 0
}

func (m *User) GetPhysicalDesk() string {
	if m != nil {
		return m.PhysicalDesk
	}
	return ""
}

func (m *User) GetService() *ServiceMsg {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *User) GetBlocked() []string {
	if m != nil {
		return m.Blocked
	}
	return nil
}

func (m *User) GetExtra() map[string]string {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *User) GetList() []*ServiceMsg {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *User) GetSex() User_Sex {
	if m != nil {
		return m.Sex
	}
	return User_SEX_NOT_KNOWN
}

type Parent struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Child                *Parent_Child `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Parent) Reset()         { *m = Parent{} }
func (m *Parent) String() string { return proto.CompactTextString(m) }
func (*Parent) ProtoMessage()    {}
func (*Parent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1}
}

func (m *Parent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent.Unmarshal(m, b)
}
func (m *Parent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent.Marshal(b, m, deterministic)
}
func (m *Parent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent.Merge(m, src)
}
func (m *Parent) XXX_Size() int {
	return xxx_messageInfo_Parent.Size(m)
}
func (m *Parent) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent.DiscardUnknown(m)
}

var xxx_messageInfo_Parent proto.InternalMessageInfo

func (m *Parent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Parent) GetChild() *Parent_Child {
	if m != nil {
		return m.Child
	}
	return nil
}

type Parent_Child struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GrandChild           *Parent_Child_GrandChild `protobuf:"bytes,2,opt,name=grand_child,json=grandChild,proto3" json:"grand_child,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Parent_Child) Reset()         { *m = Parent_Child{} }
func (m *Parent_Child) String() string { return proto.CompactTextString(m) }
func (*Parent_Child) ProtoMessage()    {}
func (*Parent_Child) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1, 0}
}

func (m *Parent_Child) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent_Child.Unmarshal(m, b)
}
func (m *Parent_Child) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent_Child.Marshal(b, m, deterministic)
}
func (m *Parent_Child) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent_Child.Merge(m, src)
}
func (m *Parent_Child) XXX_Size() int {
	return xxx_messageInfo_Parent_Child.Size(m)
}
func (m *Parent_Child) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent_Child.DiscardUnknown(m)
}

var xxx_messageInfo_Parent_Child proto.InternalMessageInfo

func (m *Parent_Child) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Parent_Child) GetGrandChild() *Parent_Child_GrandChild {
	if m != nil {
		return m.GrandChild
	}
	return nil
}

type Parent_Child_GrandChild struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parent_Child_GrandChild) Reset()         { *m = Parent_Child_GrandChild{} }
func (m *Parent_Child_GrandChild) String() string { return proto.CompactTextString(m) }
func (*Parent_Child_GrandChild) ProtoMessage()    {}
func (*Parent_Child_GrandChild) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1, 0, 0}
}

func (m *Parent_Child_GrandChild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent_Child_GrandChild.Unmarshal(m, b)
}
func (m *Parent_Child_GrandChild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent_Child_GrandChild.Marshal(b, m, deterministic)
}
func (m *Parent_Child_GrandChild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent_Child_GrandChild.Merge(m, src)
}
func (m *Parent_Child_GrandChild) XXX_Size() int {
	return xxx_messageInfo_Parent_Child_GrandChild.Size(m)
}
func (m *Parent_Child_GrandChild) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent_Child_GrandChild.DiscardUnknown(m)
}

var xxx_messageInfo_Parent_Child_GrandChild proto.InternalMessageInfo

func (m *Parent_Child_GrandChild) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Event struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*Event_Update_
	//	*Event_Delete_
	Event                isEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{2}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_Update_ struct {
	Update *Event_Update `protobuf:"bytes,3,opt,name=update,proto3,oneof"`
}

type Event_Delete_ struct {
	Delete *Event_Delete `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

func (*Event_Update_) isEvent_Event() {}

func (*Event_Delete_) isEvent_Event() {}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Event) GetUpdate() *Event_Update {
	if x, ok := m.GetEvent().(*Event_Update_); ok {
		return x.Update
	}
	return nil
}

func (m *Event) GetDelete() *Event_Delete {
	if x, ok := m.GetEvent().(*Event_Delete_); ok {
		return x.Delete
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_Update_)(nil),
		(*Event_Delete_)(nil),
	}
}

type Event_Update struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_Update) Reset()         { *m = Event_Update{} }
func (m *Event_Update) String() string { return proto.CompactTextString(m) }
func (*Event_Update) ProtoMessage()    {}
func (*Event_Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{2, 0}
}

func (m *Event_Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Update.Unmarshal(m, b)
}
func (m *Event_Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Update.Marshal(b, m, deterministic)
}
func (m *Event_Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Update.Merge(m, src)
}
func (m *Event_Update) XXX_Size() int {
	return xxx_messageInfo_Event_Update.Size(m)
}
func (m *Event_Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Update proto.InternalMessageInfo

func (m *Event_Update) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Event_Delete struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_Delete) Reset()         { *m = Event_Delete{} }
func (m *Event_Delete) String() string { return proto.CompactTextString(m) }
func (*Event_Delete) ProtoMessage()    {}
func (*Event_Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{2, 1}
}

func (m *Event_Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Delete.Unmarshal(m, b)
}
func (m *Event_Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Delete.Marshal(b, m, deterministic)
}
func (m *Event_Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Delete.Merge(m, src)
}
func (m *Event_Delete) XXX_Size() int {
	return xxx_messageInfo_Event_Delete.Size(m)
}
func (m *Event_Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Delete proto.InternalMessageInfo

func (m *Event_Delete) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ServiceMsg struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceMsg) Reset()         { *m = ServiceMsg{} }
func (m *ServiceMsg) String() string { return proto.CompactTextString(m) }
func (*ServiceMsg) ProtoMessage()    {}
func (*ServiceMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{3}
}

func (m *ServiceMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceMsg.Unmarshal(m, b)
}
func (m *ServiceMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceMsg.Marshal(b, m, deterministic)
}
func (m *ServiceMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceMsg.Merge(m, src)
}
func (m *ServiceMsg) XXX_Size() int {
	return xxx_messageInfo_ServiceMsg.Size(m)
}
func (m *ServiceMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceMsg proto.InternalMessageInfo

func (m *ServiceMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("example.User_Sex", User_Sex_name, User_Sex_value)
	proto.RegisterType((*User)(nil), "example.User")
	proto.RegisterMapType((map[string]string)(nil), "example.User.ExtraEntry")
	proto.RegisterType((*Parent)(nil), "example.Parent")
	proto.RegisterType((*Parent_Child)(nil), "example.Parent.Child")
	proto.RegisterType((*Parent_Child_GrandChild)(nil), "example.Parent.Child.GrandChild")
	proto.RegisterType((*Event)(nil), "example.Event")
	proto.RegisterType((*Event_Update)(nil), "example.Event.Update")
	proto.RegisterType((*Event_Delete)(nil), "example.Event.Delete")
	proto.RegisterType((*ServiceMsg)(nil), "example.ServiceMsg")
}

func init() { proto.RegisterFile("example/example.proto", fileDescriptor_1c78cffa5d645ba4) }

var fileDescriptor_1c78cffa5d645ba4 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xdd, 0x6e, 0xda, 0x4c,
	0x10, 0x86, 0x63, 0x8c, 0x01, 0x0f, 0x3f, 0x1f, 0xd9, 0xaf, 0xa9, 0x56, 0xa8, 0x07, 0x96, 0x53,
	0xa9, 0x96, 0xaa, 0x9a, 0x8a, 0x9e, 0x44, 0x3d, 0x83, 0xc4, 0xfd, 0x51, 0x89, 0x83, 0x4c, 0xa3,
	0xf6, 0xcc, 0x5a, 0xf0, 0x94, 0x58, 0x18, 0xb0, 0x6c, 0x83, 0x4c, 0x2e, 0xa0, 0x77, 0xd1, 0xdb,
	0xa8, 0x7a, 0xd6, 0x3b, 0xab, 0xaa, 0x5d, 0x63, 0xa0, 0xc0, 0x11, 0x3b, 0xf3, 0x3e, 0xf3, 0xce,
	0x0e, 0x9e, 0x85, 0x0b, 0x4c, 0xd9, 0x2c, 0x0c, 0xb0, 0xbd, 0xf9, 0x35, 0xc3, 0x68, 0x91, 0x2c,
	0x48, 0x79, 0x13, 0xb6, 0xea, 0x8f, 0x2c, 0x6c, 0x3f, 0xb2, 0x30, 0xcb, 0xeb, 0xdf, 0x8b, 0x50,
	0xbc, 0x8f, 0x31, 0x22, 0x0d, 0x28, 0xf8, 0x1e, 0x95, 0x34, 0xc9, 0x50, 0x9d, 0x82, 0xef, 0x91,
	0xe7, 0x00, 0xdf, 0xfc, 0x28, 0x4e, 0xdc, 0x39, 0x9b, 0x21, 0x2d, 0xf0, 0x7c, 0x4f, 0xf9, 0xf5,
	0xe7, 0x87, 0x2c, 0x39, 0xaa, 0x10, 0x6c, 0x36, 0x43, 0xa2, 0x83, 0x1a, 0xb0, 0x1c, 0x92, 0xf7,
	0xa1, 0x0a, 0xcf, 0x0b, 0xc6, 0x84, 0xff, 0x70, 0x16, 0x06, 0x8b, 0x35, 0xa2, 0x3b, 0x5f, 0xce,
	0x46, 0x18, 0xd1, 0xa2, 0x26, 0x19, 0x72, 0x4e, 0x36, 0x72, 0xd5, 0x16, 0x22, 0xb9, 0x84, 0x7a,
	0xf8, 0xb0, 0x8e, 0xfd, 0x31, 0x0b, 0x5c, 0x0f, 0xe3, 0x29, 0x2d, 0x89, 0x4b, 0xd5, 0xf2, 0xe4,
	0x0d, 0xc6, 0x53, 0xf2, 0x0a, 0xca, 0x31, 0x46, 0x2b, 0x7f, 0x8c, 0xb4, 0xa2, 0x49, 0x46, 0xb5,
	0xf3, 0xbf, 0x99, 0x0f, 0x3c, 0xcc, 0xf2, 0xb7, 0xf1, 0xc4, 0xc9, 0x19, 0x42, 0xa1, 0x3c, 0x0a,
	0x16, 0xe3, 0x29, 0x7a, 0x54, 0xd5, 0x64, 0x43, 0x75, 0xf2, 0x90, 0x98, 0xa0, 0x60, 0x9a, 0x44,
	0x8c, 0x82, 0x26, 0x1b, 0xd5, 0x0e, 0xdd, 0xda, 0xf0, 0x7f, 0xc5, 0xb4, 0xb8, 0x64, 0xcd, 0x93,
	0x68, 0xed, 0x64, 0x18, 0x79, 0x01, 0xc5, 0xc0, 0x8f, 0x13, 0x5a, 0x15, 0xf8, 0xc9, 0xae, 0x02,
	0x20, 0x97, 0x20, 0xc7, 0x98, 0xd2, 0x9a, 0x26, 0x19, 0x8d, 0xce, 0xf9, 0xbf, 0xb6, 0x43, 0x4c,
	0x1d, 0xae, 0xb6, 0xae, 0x00, 0x76, 0x2d, 0x48, 0x13, 0xe4, 0x29, 0xae, 0x37, 0x1f, 0x81, 0x1f,
	0xc9, 0x13, 0x50, 0x56, 0x2c, 0x58, 0x6e, 0x3e, 0x80, 0x93, 0x05, 0x6f, 0x0b, 0x57, 0x92, 0x6e,
	0x83, 0x3c, 0xc4, 0x94, 0x9c, 0x43, 0x7d, 0x68, 0x7d, 0x75, 0xed, 0xbb, 0xcf, 0xee, 0x27, 0xfb,
	0xee, 0x8b, 0xdd, 0x3c, 0x23, 0x35, 0xa8, 0xf0, 0xd4, 0x6d, 0xb7, 0x6f, 0x35, 0x25, 0xd2, 0x00,
	0xe0, 0xd1, 0x3b, 0x4b, 0xc4, 0x05, 0xf2, 0x14, 0x48, 0x5e, 0xd0, 0x1d, 0x0c, 0xfa, 0x1f, 0xaf,
	0xbb, 0xbd, 0xbe, 0xd5, 0x54, 0xf5, 0xdf, 0x12, 0x94, 0x06, 0x2c, 0xc2, 0x79, 0x72, 0xb4, 0x0a,
	0x2f, 0x41, 0x19, 0x3f, 0xf8, 0x81, 0x27, 0x2e, 0x51, 0xed, 0x5c, 0x6c, 0x67, 0xc9, 0x78, 0xf3,
	0x9a, 0x8b, 0x4e, 0xc6, 0xb4, 0x52, 0x50, 0x44, 0x7c, 0xe4, 0xd2, 0x85, 0xea, 0x24, 0x62, 0x73,
	0xcf, 0xdd, 0xf7, 0xd2, 0x4e, 0x7a, 0x99, 0xef, 0x39, 0x98, 0xd9, 0xc2, 0x64, 0x7b, 0x6e, 0x3d,
	0x03, 0xd8, 0x29, 0x87, 0x0d, 0xf4, 0x9f, 0x12, 0x28, 0xd6, 0xea, 0xd4, 0x00, 0x6d, 0x28, 0x2d,
	0x43, 0x8f, 0x25, 0xd9, 0x8a, 0xee, 0x4f, 0x20, 0x78, 0xf3, 0x5e, 0x88, 0x1f, 0xce, 0x9c, 0x0d,
	0xc6, 0x0b, 0x3c, 0x0c, 0x30, 0x41, 0xb1, 0xa9, 0xc7, 0x05, 0x37, 0x42, 0xe4, 0x05, 0x19, 0xd6,
	0xa2, 0x50, 0xca, 0x4c, 0x0e, 0x7b, 0x73, 0x25, 0xa3, 0x0f, 0x95, 0x5e, 0x19, 0x14, 0xe4, 0x6e,
	0xfa, 0x6b, 0x80, 0xdd, 0xf6, 0x1c, 0x5d, 0x9e, 0x40, 0x71, 0xf7, 0x04, 0x1d, 0x71, 0x1e, 0x95,
	0xc4, 0xe3, 0x7d, 0xf3, 0x37, 0x00, 0x00, 0xff, 0xff, 0x35, 0x82, 0xeb, 0xe9, 0xed, 0x03, 0x00,
	0x00,
}
