// Code generated by protoc-gen-defaults. DO NOT EDIT.

package example

import (
	"go.uber.org/zap/zapcore"
)

func (u *User) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("id", u.Id)

	enc.AddString("physical_desk", u.PhysicalDesk)

	enc.AddObject("service", u.Service)

	blockedArrMarshaller := func(enc zapcore.ArrayEncoder) error {
		for _, v := range u.Blocked {
			enc.AppendString(v)

		}
		return nil
	}
	enc.AddArray("blocked", zapcore.ArrayMarshalerFunc(blockedArrMarshaller))

	// TODO optimize map value type
	enc.AddReflected("extra", u.Extra)

	listArrMarshaller := func(enc zapcore.ArrayEncoder) error {
		for _, v := range u.List {
			enc.AppendObject(v)
		}
		return nil
	}
	enc.AddArray("list", zapcore.ArrayMarshalerFunc(listArrMarshaller))

	return nil
}

func (u *Parent) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("id", u.Id)

	enc.AddObject("child", u.Child)

	return nil
}

func (u *Event) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("id", u.Id)

	enc.AddObject("update", u.GetUpdate())

	enc.AddObject("delete", u.GetDelete())

	return nil
}

func (u *ServiceMsg) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("id", u.Id)

	enc.AddString("name", u.Name)

	return nil
}

func (u *Parent_Child) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("id", u.Id)

	enc.AddObject("grand_child", u.GrandChild)

	return nil
}

func (u *Parent_Child_GrandChild) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("id", u.Id)

	return nil
}

func (u *Event_Update) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("id", u.Id)

	return nil
}

func (u *Event_Delete) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("id", u.Id)

	return nil
}
