// Code generated by protoc-gen-defaults. DO NOT EDIT.

package example

import (
	"github.com/golang/protobuf/ptypes"
	"go.uber.org/zap/zapcore"
	"time"
)

func (u *User) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("Id:", u.Id)

	enc.AddString("PhysicalDesk:", u.PhysicalDesk)

	enc.AddObject("Service:", u.Service)

	BlockedArrMarshaller := func(enc zapcore.ArrayEncoder) error {
		for _, v := range u.Blocked {
			enc.AppendString(v)

		}
		return nil
	}
	enc.AddArray("Blocked:", zapcore.ArrayMarshalerFunc(BlockedArrMarshaller))

	enc.AddReflected("Extra:", u.Extra)

	ListArrMarshaller := func(enc zapcore.ArrayEncoder) error {
		for _, v := range u.List {
			enc.AppendObject(v)

		}
		return nil
	}
	enc.AddArray("List:", zapcore.ArrayMarshalerFunc(ListArrMarshaller))

	return nil
}

func (u *Parent) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("Id:", u.Id)

	enc.AddObject("Child:", u.Child)

	return nil
}

func (u *Event) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("Id:", u.Id)

	enc.AddObject("Update:", u.GetUpdate())

	enc.AddObject("Delete:", u.GetDelete())

	return nil
}

func (u *ServiceMsg) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("Id:", u.Id)

	enc.AddString("Name:", u.Name)

	return nil
}

func (u *Parent_Child) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("Id:", u.Id)

	enc.AddObject("GrandChild:", u.GrandChild)

	return nil
}

func (u *Parent_Child_GrandChild) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("Id:", u.Id)

	return nil
}

func (u *Event_Update) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("Id:", u.Id)

	return nil
}

func (u *Event_Delete) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if u == nil {
		return nil
	}

	enc.AddString("Id:", u.Id)

	return nil
}
